### ISSUE TITLE
monitoring crashes if the app has an error while starting app and user clicks "OK" on error prompt

### ISSUE THREAD

**Issue by MegaJSDeveloper** [catdad/electronmon#40]
if i get error like this:

`main.js` :
```javascript
console.log(qqq) // qqq is not defined
```

and press Ctrl + S, my electronmon restart with error,

and if i after this `qqq` replase  to `232332`
`main.js` :
```javascript
console.log(232332) // qqq is not defined
```
my electronmon app not restarting
it my console output:

```cmd
 App threw an error during load
ReferenceError: qq is not defined
    at Object.<anonymous> (C:\localhost\electron\index.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (C:\localhost\electron\node_modules\runtime-required\runtime-required.js:38:23)
    at loadApplicationPackage (C:\localhost\electron\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)
    at Object.<anonymous> (C:\localhost\electron\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
C:\localhost\electron\node_modules\electronmon\src\electronmon.js:86
  globalApp.once('exit', () => {
            ^

TypeError: Cannot read property 'once' of null
    at restartApp (C:\localhost\electron\node_modules\electronmon\src\electronmon.js:86:13)
    at FSWatcher.<anonymous> (C:\localhost\electron\node_modules\electronmon\src\electronmon.js:102:14)
    at FSWatcher.emit (events.js:210:5)
    at FSWatcher.<anonymous> (C:\localhost\electron\node_modules\chokidar\index.js:199:15)
    at FSWatcher._emit (C:\localhost\electron\node_modules\chokidar\index.js:241:5)
    at FSWatcher.<anonymous> (C:\localhost\electron\node_modules\chokidar\lib\nodefs-handler.js:274:18)
    at FSReqCallback.oncomplete (fs.js:159:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 electronmon: `electronmon .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 electronmon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-12-17T01_27_21_582Z-debug.log

```

**Comment by catdad** [comment]
I am guessing that you are clicking "OK" on the message box that pops up in that case? I have a test case for when you don't click "OK" and just edit the file to fix the error, but I haven't found a good way to interact with the prompts in a test, so I missed this one. Anyway, the fix is simple, and I am pushing that now.

**Comment by MegaJSDeveloper** [comment]
@catdad tell me where can I throw you money! you do an incredible job! Your project must have thousands of stars! I don’t understand why this is not so! give the card number, I'll throw you the money! I am from Russia, I am poor, but I will give money as much as I can! if it weren’t for your project, I couldn’t make money at all!

**Comment by catdad** [comment]
Don't worry about money, just tell all your friends about my projects. I appreciate all the community involvement. I;m glad you're getting use out of this project.

**Comment by catdad** [comment]
Fix published in 0.7.1.

**Comment by MegaJSDeveloper** [comment]
@catdad thanks a lot! from our entire Russian team!

**Comment by MegaJSDeveloper** [comment]
@catdad you are an amazing person, i will do it! =)
