### ISSUE TITLE
"path" argument must be of type string - `electronmon` fails to load app due to bug in `runtime-required` dependency

### ISSUE THREAD

**Issue by tranhl** [catdad/electronmon#61]
Using Electron React Boilerplate v2, `electronmon` fails to start with the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
	  at validateString (internal/validators.js:120:11)
	  at Object.dirname (path.js:1128:5)
	  at Function.Module._load (/Users/longt/Documents/projects/solta/liverton.desktop.terminal-agent/node_modules/runtime-required/runtime-required.js:31:40)
	  at Module.require (internal/modules/cjs/loader.js:1032:19)
	  at Function.Module._preloadModules (internal/modules/cjs/loader.js:1293:12)
	  at Object.<anonymous> (/Users/longt/Documents/projects/solta/liverton.desktop.terminal-agent/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:67:12)
	  at Module._compile (internal/modules/cjs/loader.js:1152:30)
	  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
	  at Module.load (internal/modules/cjs/loader.js:992:32)
	  at Module._load (internal/modules/cjs/
```

This is because in [runtime-requried](https://github.com/catdad/runtime-required/blob/e09ad81125d46e16ccead562ef43b154cd5b8596/runtime-required.js#L31), it is incorrectly assumed that if `parent` is not nil, then `parent.filename` is also not nil. It turns out that this is not the case, and that `parent.filename` can be `null`. The fix here would be to simply check for `parent.filename` before passing it to `path.dirname()`.

For anyone currently affected by this and needs a temporary workaround, I've written a script that patches `node_modules/runtime-required/runtime-required.js` and added it to as a package.json script under `prestart:main`:

```
// .erb/scripts/PatchElectronmon.js
const fs = require('fs')
const path = require('path')

const runtimeRequired = fs.readFileSync(path.join(__dirname, './runtime-required.js'))

fs.writeFileSync(
  path.join(process.cwd(),
  'node_modules/runtime-required/runtime-required.js'),
  runtimeRequired
)

// package.json
{
	"scripts": {
+     "prestart:main": "node ./.erb/scripts/PatchElectronmon.js",
    }
}

// .erb/scripts/runtime-required.js
const path = require('path');
const Module = require('module');
const EventEmitter = require('events');

const resolve = require('resolve-from');

const events = new EventEmitter();

const emit = (request, id) => {
  var type = 'file';

  if (id.indexOf('node_modules') > -1) {
    type = 'module';
  } else if (!path.parse(id).root) {
    type = 'builtin';
  }

  events.emit('file', {
    type: type,
    id: id
  });
};

// this is a hack and I don't like it
// if you know a better way to collect all required modules
// please file an issue, I'd appreciate it very much
// https://github.com/catdad/electronmon/issues/new
const originalLoad = Module._load;
Module._load = function (request, parent) {
  if (parent && parent.filename) {
    const idpath = resolve.silent(path.dirname(parent.filename), request);

    if (idpath) {
      emit(request, idpath);
    }
  }

  return originalLoad.apply(this, arguments);
};

module.exports = events;
```

**Comment by catdad** [comment]
`runtime-required` has been fixed for a few days now, but I just made that version the minimum required for `electronmon`. This should be fixed in version 2.0.2.
